### PR TITLE
Fixed github link

### PR DESCRIPTION
**Pull request by Kite1024**
because yay, this needs a branch ;)

### CODE REVIEW

**Comment by ArjanSeijs** [comment]
Kan je *.pyc aan de gitignore toevoegen en de gecompileede files verwijderen?

**Comment by Kite1024** [comment]
Done and done.
Also fixed the icons except for the dragon, but the code should be fine for that one maybe it's on their side.

**Comment by Kite1024** [comment]
* Wel in andere PR :)

**Comment by Kite1024** [comment]
Already in #6 .

**Pull request closed without merging**
